apiVersion: appprotect.f5.com/v1beta1
kind: APPolicy
metadata: 
  name: appolicy-api
spec:
  policy:
    name: appolicy-api
    template: 
      name: POLICY_TEMPLATE_NGINX_BASE
    applicationLanguage: utf-8
    enforcementMode: blocking
    open-api-files: 
    - link: "https://raw.githubusercontent.com/mcheo-nginx/sample-files/main/simplified-httpbin-oas.json"
    blocking-settings:
      violations:
      - name: VIOL_FILE_UPLOAD_IN_BODY
        alarm: true
        block: true
      - name: VIOL_MANDATORY_REQUEST_BODY
        alarm: true
        block: true
      - name: VIOL_PARAMETER_LOCATION
        alarm: true
        block: true
      - name: VIOL_MANDATORY_PARAMETER
        alarm: true
        block: true
      - name: VIOL_JSON_SCHEMA
        alarm: true
        block: true
      - name: VIOL_FILE_UPLOAD
        alarm: true
        block: true
      - name: VIOL_URL_CONTENT_TYPE
        alarm: true
        block: true
      - name: VIOL_PARAMETER_STATIC_VALUE
        alarm: true
        block: true
      - name: VIOL_PARAMETER_VALUE_LENGTH
        alarm: true
        block: true
      - name: VIOL_PARAMETER_DATA_TYPE
        alarm: true
        block: true
      - name: VIOL_PARAMETER_NUMERIC_VALUE
        alarm: true
        block: true
      - name: VIOL_URL
        alarm: true
        block: true
      - name: VIOL_PARAMETER
        alarm: true
        block: true
      - name: VIOL_PARAMETER_EMPTY_VALUE
        alarm: true
        block: true
      - name: VIOL_PARAMETER_REPEATED
        alarm: true
        block: true